name: Build and Upload Release Packages

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build web assets
        run: make web

      - name: Build packages
        run: |
          make build
          bash package.sh

      - name: Upload packages to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
